# Generated by Django 6.1.1 on 2026-09-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_types', to='tags.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='tags.dealer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_no', models.CharField(max_length=50, unique=True)),
                ('lot', models.CharField(blank=True, max_length=50)),
                ('vi_size', models.CharField(blank=True, max_length=10)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='tags.dealer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='tags.vehiclemodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_raised', models.DateField()),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('part_name', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_description', models.TextField()),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('action_taken', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Closed')], default='P', max_length=10)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, choices=[('EOL', 'End of Line'), ('FINAL', 'Final'), ('OTHER', 'Other')], max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_tags', to='tags.category')),
                ('issue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_tags', to='tags.issuetype')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_raised', to='tags.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_verified', to='tags.employee')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_tags', to='tags.section')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_tags', to='tags.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_tags', to='tags.vehicle')),
            ],
            options={
                'ordering': ['-date_raised', '-id'],
                'indexes': [models.Index(fields=['status'], name='tags_redtag_status_8c7804_idx'), models.Index(fields=['date_raised'], name='tags_redtag_date_ra_4271ee_idx'), models.Index(fields=['vehicle'], name='tags_redtag_vehicle_b7e116_idx'), models.Index(fields=['section'], name='tags_redtag_section_5b4f46_idx')],
            },
        ),
    ]
