# Generated by Django 6.1.1 on 2026-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redtag',
            name='part_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='redtag',
            name='part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
