# Generated by Django 6.1.1 on 2026-09-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_widen_part_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['section__code', 'name']},
        ),
        migrations.AddField(
            model_name='station',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='tags.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('section', 'name')},
        ),
    ]
