# Generated by Django 6.1.1 on 2026-09-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_section_station_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_in_form',
            field=models.BooleanField(default=False, help_text='Include this section in the New Red Tag dropdown (List sheet master data).'),
        ),
    ]
