# Generated by Django 6.1.1 on 2026-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_section_show_in_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='show_in_form',
            field=models.BooleanField(default=False, help_text='Include this station in the New Red Tag dropdown (List sheet master data).'),
        ),
    ]
